"""real_email_verification_and_notifications

Revision ID: 02e8ce7adb94
Revises: 'a1b2c3d4e5f6'
Create Date: 2026-08-13 21:17:14.062748

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '02e8ce7adb94'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('employer_feedback', sa.Text(), nullable=True))
    op.add_column('email_verification_tokens', sa.Column('attempts_count', sa.Integer(), nullable=False))
    op.add_column('email_verification_tokens', sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('email_verification_tokens', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('resumes', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='resumestatus'),
               existing_nullable=False)
    op.alter_column('resumes', 'content',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               existing_nullable=False)
    op.alter_column('resumes', 'ai_suggestions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               existing_nullable=True)
    op.add_column('users', sa.Column('telegram_chat_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('telegram_username', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('telegram_link_code', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_users_telegram_chat_id'), 'users', ['telegram_chat_id'], unique=False)
    op.create_index(op.f('ix_users_telegram_link_code'), 'users', ['telegram_link_code'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_link_code'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_chat_id'), table_name='users')
    op.drop_column('users', 'telegram_link_code')
    op.drop_column('users', 'telegram_username')
    op.drop_column('users', 'telegram_chat_id')
    op.alter_column('resumes', 'ai_suggestions',
               existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('resumes', 'content',
               existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('resumes', 'status',
               existing_type=sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='resumestatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('email_verification_tokens', 'created_at')
    op.drop_column('email_verification_tokens', 'last_sent_at')
    op.drop_column('email_verification_tokens', 'attempts_count')
    op.drop_column('applications', 'employer_feedback')
    # ### end Alembic commands ###
